import './globals.css'
import NavBar from '@/components/NavBar'
import clsx from 'clsx'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          `${geistSans.variable} ${geistMono.variable} antialiased`,
          'bg-bg-primary text-text-primary',
          'dark:bg-bg-dk-primary dark:text-dk-text-primary'
        )}
      >
        <div className="flex min-h-screen flex-col md:flex-row">
          <NavBar />
          <main className="mt-21 flex-3 md:mt-0">{children}</main>
        </div>
      </body>
    </html>
  )
}
