import './globals.css'
import NavBar from '@/components/NavBar'
import clsx from 'clsx'
import type { Metadata } from 'next'
import { Gluten, Space_Grotesk, Notable } from 'next/font/google'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale } from 'next-intl/server'
import { Language } from '@/i18n/config'

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space-grotesk',
})

const notable = Notable({
  weight: '400',
  variable: '--font-notable',
  subsets: ['latin'],
})

const gluten = Gluten({
  weight: '300',
  variable: '--font-gluten',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()

  return (
    <html
      lang={locale}
      className={`${gluten.variable} ${spaceGrotesk.variable} ${notable.variable}`}
    >
      <body
        className={clsx(
          `font-main antialiased`,
          'bg-background text-copy',
          'dark:bg-dark-background dark:text-dark-copy'
        )}
      >
        <NextIntlClientProvider>
          <div className="flex min-h-screen flex-col md:flex-row">
            <NavBar locale={locale as Language} />
            <main className="mt-13.5 flex-7 md:mt-0">
              <div className="flex min-h-screen items-center justify-start p-10">
                {children}
              </div>
            </main>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
